### ISSUE TITLE
no working script in lambda.

### ISSUE THREAD

**Issue by manutoala** [akrylysov/lambda-phantom-scraper#1]
{
  "errorMessage": "Process exited before completing request"
}

**Comment by akrylysov** [comment]
Does cloudwatch logs show any errors?

**Comment by manutoala** [comment]
START RequestId: 0a8ba602-9c8b-11e6-8685-b534d911b2bb Version: $LATEST
2016-10-27T21:19:27.929Z    0a8ba602-9c8b-11e6-8685-b534d911b2bb    { url: 'https://consultas.curp.gob.mx/CurpSP/' }
END RequestId: 0a8ba602-9c8b-11e6-8685-b534d911b2bb
REPORT RequestId: 0a8ba602-9c8b-11e6-8685-b534d911b2bb  Duration: 115.49 ms Billed Duration: 200 ms Memory Size: 128 MB Max Memory Used: 13 MB  
Process exited before completing request

**Comment by akrylysov** [comment]
PhantomJS requires more than 128 MB of memory, try at least 512.

**Comment by manutoala** [comment]
START RequestId: 96cf9fc6-9cbd-11e6-a0ed-17678d5942a9 Version: $LATEST
2016-10-28T03:21:17.731Z    96cf9fc6-9cbd-11e6-a0ed-17678d5942a9    { url: 'https://consultas.curp.gob.mx/CurpSP/' }
END RequestId: 96cf9fc6-9cbd-11e6-a0ed-17678d5942a9
REPORT RequestId: 96cf9fc6-9cbd-11e6-a0ed-17678d5942a9  Duration: 27.63 ms  Billed Duration: 100 ms     Memory Size: 1536 MB    Max Memory Used: 5 MB  
Process exited before completing request

No working :/

**Comment by akrylysov** [comment]
Sorry, can't reproduce the issue, did you upload zip file from `dist` directory after running `build.sh`?
